//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Projesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tez
    {
        public int Ogrenci_Id { get; set; }
        public int Danisman_Id { get; set; }
        public string Abstract { get; set; }
        public int Donem { get; set; }
    
        public virtual Ogrenci Ogrenci { get; set; }
        public virtual Ogretim_Uyesi Ogretim_Uyesi { get; set; }
    }
}
